### ISSUE TITLE
Trocar Alert no Android

### ISSUE THREAD

**Issue by MatheusCoxxxta** [julianotavares/gobarber-project#77]
Usando o `Platform` do React Native dá pra verificar o OS do dispositivo. No IOS o `Alert` fica bem legal, é bem bonito. No Android seria mais legal utilizar um `ToastAndroid` ou algum tipo de Snackbar para substituir o `Alert`.

Mas é só uma dica de melhoria 👍

**Comment by julianotavares** [comment]
Obrigado pela dica Matheus, com certeza irei implementar essas features, vlw!
